name: pytorch-bsf
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.9
- cudatoolkit=10.2
- pytorch=1.8.1
- pytorch-lightning=1.3.7
- torchvision=0.9.1  # only used for mlflow
- mlflow=1.18.0
