name: pytorch-bsf
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.9
- cudatoolkit=10.2
- pytorch=1.8.2
- pytorch-lightning=1.7.3
- torchvision=0.13.1  # only used for mlflow
- mlflow=1.28.0
