name: pytorch-bsf
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.11
- cudatoolkit
- pytorch
- pytorch-lightning
- torchmetrics
- torchvision  # only used for mlflow
- mlflow
- jsonschema
