name: pytorch-bsf
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.11
- cudatoolkit
- pytorch
- lightning
- pl-crossvalidate
- torchmetrics
- torchvision  # only used for mlflow
- mlflow
- jsonschema
- pyyaml
