name: pytorch-bsf
channels:
- pytorch
- conda-forge
- defaults
dependencies:
- python=3.13
- cudatoolkit
- pytorch
- lightning
- torchmetrics
- mlflow
- jsonschema
- pyyaml
- pip
- pip:
  - pl-crossvalidate
