name: GHPages

on:
 push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Sphinx Pages
      uses: cor3ntin/sphinx-action@main
      with:
        docs-folder: docs/
        pre-build-command: |
          apt-get update
          apt-get install -y git
          git config --global --add safe.directory /github/workspace
        build-command: sphinx-multiversion . _build
    - name: Commit documentation changes
      run: |
        git clone ${{ github.server_url }}/${{ github.repository }} --branch gh-pages --single-branch gh-pages
        cp -r docs/_build/* gh-pages/
        cd gh-pages
        echo "GitHub Pages of [${{ github.repository }}](${{ github.server_url }}/${{ github.repository }})" > README.md
        echo "===" >> README.md
        echo "Sphinx html documentation of [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/tree/${{ github.sha }})" >> README.md
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit --allow-empty -m "From ${{ github.ref }} ${{ github.sha }}"
        # The above command will fail if no changes were present, so we ignore
        # the return code.
    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        branch: gh-pages
        directory: gh-pages
        github_token: ${{ secrets.GITHUB_TOKEN }}
